// Code generated by MockGen. DO NOT EDIT.
// Source: domain/ledger/repository.go
//
// Generated by this command:
//
//	mockgen -source=domain/ledger/repository.go -destination=domain/ledger/mock_repository.go -package=ledger
//

// Package ledger is a generated GoMock package.
package ledger

import (
	context "context"
	reflect "reflect"

	models "github.com/akeren/go-api-foundry/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLedgerRepository is a mock of LedgerRepository interface.
type MockLedgerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerRepositoryMockRecorder
	isgomock struct{}
}

// MockLedgerRepositoryMockRecorder is the mock recorder for MockLedgerRepository.
type MockLedgerRepositoryMockRecorder struct {
	mock *MockLedgerRepository
}

// NewMockLedgerRepository creates a new mock instance.
func NewMockLedgerRepository(ctrl *gomock.Controller) *MockLedgerRepository {
	mock := &MockLedgerRepository{ctrl: ctrl}
	mock.recorder = &MockLedgerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerRepository) EXPECT() *MockLedgerRepositoryMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockLedgerRepository) CreateAccount(ctx context.Context, account *models.Account) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, account)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockLedgerRepositoryMockRecorder) CreateAccount(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockLedgerRepository)(nil).CreateAccount), ctx, account)
}

// ExecuteDoubleEntry mocks base method.
func (m *MockLedgerRepository) ExecuteDoubleEntry(ctx context.Context, cmd DoubleEntryCommand) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDoubleEntry", ctx, cmd)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteDoubleEntry indicates an expected call of ExecuteDoubleEntry.
func (mr *MockLedgerRepositoryMockRecorder) ExecuteDoubleEntry(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDoubleEntry", reflect.TypeOf((*MockLedgerRepository)(nil).ExecuteDoubleEntry), ctx, cmd)
}

// GetAccountByID mocks base method.
func (m *MockLedgerRepository) GetAccountByID(ctx context.Context, id string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", ctx, id)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockLedgerRepositoryMockRecorder) GetAccountByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockLedgerRepository)(nil).GetAccountByID), ctx, id)
}

// GetAllAccountsForReconciliation mocks base method.
func (m *MockLedgerRepository) GetAllAccountsForReconciliation(ctx context.Context) ([]AccountReconciliation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccountsForReconciliation", ctx)
	ret0, _ := ret[0].([]AccountReconciliation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAccountsForReconciliation indicates an expected call of GetAllAccountsForReconciliation.
func (mr *MockLedgerRepositoryMockRecorder) GetAllAccountsForReconciliation(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccountsForReconciliation", reflect.TypeOf((*MockLedgerRepository)(nil).GetAllAccountsForReconciliation), ctx)
}

// GetDerivedBalance mocks base method.
func (m *MockLedgerRepository) GetDerivedBalance(ctx context.Context, accountID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDerivedBalance", ctx, accountID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDerivedBalance indicates an expected call of GetDerivedBalance.
func (mr *MockLedgerRepositoryMockRecorder) GetDerivedBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDerivedBalance", reflect.TypeOf((*MockLedgerRepository)(nil).GetDerivedBalance), ctx, accountID)
}

// GetTransactionsByAccountID mocks base method.
func (m *MockLedgerRepository) GetTransactionsByAccountID(ctx context.Context, accountID string, limit, offset int) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByAccountID", ctx, accountID, limit, offset)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByAccountID indicates an expected call of GetTransactionsByAccountID.
func (mr *MockLedgerRepositoryMockRecorder) GetTransactionsByAccountID(ctx, accountID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByAccountID", reflect.TypeOf((*MockLedgerRepository)(nil).GetTransactionsByAccountID), ctx, accountID, limit, offset)
}
