// Code generated by MockGen. DO NOT EDIT.
// Source: domain/waitlist/repository.go
//
// Generated by this command:
//
//	mockgen -source=domain/waitlist/repository.go -destination=domain/waitlist/mock_repository.go -package=waitlist
//

// Package waitlist is a generated GoMock package.
package waitlist

import (
	context "context"
	reflect "reflect"

	models "github.com/akeren/go-api-foundry/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockWaitlistRepository is a mock of WaitlistRepository interface.
type MockWaitlistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWaitlistRepositoryMockRecorder
	isgomock struct{}
}

// MockWaitlistRepositoryMockRecorder is the mock recorder for MockWaitlistRepository.
type MockWaitlistRepositoryMockRecorder struct {
	mock *MockWaitlistRepository
}

// NewMockWaitlistRepository creates a new mock instance.
func NewMockWaitlistRepository(ctrl *gomock.Controller) *MockWaitlistRepository {
	mock := &MockWaitlistRepository{ctrl: ctrl}
	mock.recorder = &MockWaitlistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWaitlistRepository) EXPECT() *MockWaitlistRepositoryMockRecorder {
	return m.recorder
}

// CreateEntry mocks base method.
func (m *MockWaitlistRepository) CreateEntry(ctx context.Context, entry *models.WaitlistEntry) (*models.WaitlistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntry", ctx, entry)
	ret0, _ := ret[0].(*models.WaitlistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntry indicates an expected call of CreateEntry.
func (mr *MockWaitlistRepositoryMockRecorder) CreateEntry(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntry", reflect.TypeOf((*MockWaitlistRepository)(nil).CreateEntry), ctx, entry)
}

// DeleteEntry mocks base method.
func (m *MockWaitlistRepository) DeleteEntry(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEntry", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry.
func (mr *MockWaitlistRepositoryMockRecorder) DeleteEntry(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockWaitlistRepository)(nil).DeleteEntry), ctx, id)
}

// FindEntryByID mocks base method.
func (m *MockWaitlistRepository) FindEntryByID(ctx context.Context, id uint) (*models.WaitlistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEntryByID", ctx, id)
	ret0, _ := ret[0].(*models.WaitlistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEntryByID indicates an expected call of FindEntryByID.
func (mr *MockWaitlistRepositoryMockRecorder) FindEntryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEntryByID", reflect.TypeOf((*MockWaitlistRepository)(nil).FindEntryByID), ctx, id)
}

// GetAllEntries mocks base method.
func (m *MockWaitlistRepository) GetAllEntries(ctx context.Context) ([]*models.WaitlistEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEntries", ctx)
	ret0, _ := ret[0].([]*models.WaitlistEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEntries indicates an expected call of GetAllEntries.
func (mr *MockWaitlistRepositoryMockRecorder) GetAllEntries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEntries", reflect.TypeOf((*MockWaitlistRepository)(nil).GetAllEntries), ctx)
}

// UpdateEntry mocks base method.
func (m *MockWaitlistRepository) UpdateEntry(ctx context.Context, id uint, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEntry", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEntry indicates an expected call of UpdateEntry.
func (mr *MockWaitlistRepositoryMockRecorder) UpdateEntry(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntry", reflect.TypeOf((*MockWaitlistRepository)(nil).UpdateEntry), ctx, id, updates)
}
